# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YZ5GwMBMXF45p4dN2Av2c4xtjN4UChR2
"""

def find_busiest_intersections(data) :
  output = []
  max=0
  count=0
  for member in data :
    if  max <= data.get(member):

      max=data.get(member)
      count+=1
      output.append(max)
  return output,count

find_busiest_intersections(data=dict({"1":1,"2":2,"3":3,"4":4,"5":4}))

from typing import KeysView
data=dict({"1":4,"2":3,"3":2,"4":4,"5":1})
data.pop("1")
for member in data :
  print(member)
print(data.items)